version: "3.8"

services:
  postgresql:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
